on:
  push:
    branches:
      - 'production'
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://linux135.unoeuro.com/
        ftp-username: peliarvostelut.net
        ftp-password: ${{ secrets.FTP_PASSWORD }}
